/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */

#include "../Assignment/dictionary.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

insert_out *
insert_proc_1(common_in *argp, CLIENT *clnt)
{
	static insert_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INSERT_PROC,
		(xdrproc_t) xdr_common_in, (caddr_t) argp,
		(xdrproc_t) xdr_insert_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

getmeaning_out *
getmeaning_proc_1(common_in *argp, CLIENT *clnt)
{
	static getmeaning_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETMEANING_PROC,
		(xdrproc_t) xdr_common_in, (caddr_t) argp,
		(xdrproc_t) xdr_getmeaning_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

delete_out *
delete_proc_1(common_in *argp, CLIENT *clnt)
{
	static delete_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DELETE_PROC,
		(xdrproc_t) xdr_common_in, (caddr_t) argp,
		(xdrproc_t) xdr_delete_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
